config/routes.rb
Rails.application.routes.draw do
  resources :categories
  authenticated :user, ->(user) { user.admin? } do
    get 'admin', to: 'admin#index'
    get 'admin/posts'
    get 'admin/comments'
    get 'admin/users'
    get 'admin/show_post/:id', to: 'admin#show_post', as: 'admin_post'
  end
  get 'search', to: 'search#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :after_signup

  get 'u/:id', to: 'users#profile', as: 'user'

  # /posts/1/comments/1
  resources :posts do
    resources :comments
  end
  get 'about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"
end

app/models/post.rb
# frozen_string_literal: true

# Represents a blog post in the application
class Post < ApplicationRecord
  extend FriendlyId
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :notifications, through: :user
  has_rich_text :body
  has_one :content, class_name: 'ActionText::RichText', as: :record, dependent: :destroy

  validates :title, presence: true, length: { minimum: 5, maximum: 50 }
  validates :body, presence: true, length: { minimum: 10, maximum: 1000 }

  friendly_id :title, use: %i[slugged history finders]

  def self.ransackable_attributes(auth_object = nil)
    %w[content_body created_at id title updated_at user_id views category_id]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[comments notifications user category]
  end
  
  def should_generate_new_friendly_id?
    title_changed? || slug.blank?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include Pagy::Backend

  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /posts or /posts.json
  def index
    @pagy, @posts = pagy(Post.all.includes(:user, :rich_text_body).order(created_at: :desc))
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.update(views: @post.views + 1)
    @comments = @post.comments.includes(:user, :rich_text_body).order(created_at: :desc)

    mark_notification_as_read if current_user
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])

    redirect_to @post, status: :moved_permanently if params[:id] != @post.slug
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body, :category_id)
  end

  def mark_notification_as_read
    notification_to_mark_as_read = @post.notifications.where(recipient: current_user)
    notification_to_mark_as_read.update_all(read_at: Time.zone.now)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.select :category_id, options_for_select(Category.all.order(name: :desc)
        .collect { |cat| [cat.name, cat.id] }), {}, { class: 'form-select' } %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.rich_text_area :body, class: 'form-control' %>
  </div>

  <div class="mt-3">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <h2><%= post.title %></h2>
  <h4>Created by <%= link_to post.user.full_name, user_path(post.user) %></h4>
  <h6><%= pluralize(post.views, 'view') %></h6>
  <div>
    <%= post.body %>
  </div>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
  <%== pagy_bootstrap_nav(@pagy, link_extra: 'data-turbolinks="false"') %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

<div class="container border p-3">
  <%= render 'comments/form', post: @post, comment: @post.comments.build, submit_label: 'Reply' %>
</div>
<% if @comments.size.positive? %>
  <div>
    <% @comments.each do |comment| %>  
      <%= render 'comments/comment', post: @post, comment: comment %>
    <% end %>
  </div>
<% end %>